language: node_js
node_js:
  - "4.1"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma
  - npm install -g typescript
  - ./nodeserver.sh > /dev/null &

env: 
  matrix:
    # CORE_BRANCH specifies the branch of ui-router-core to include during build/test
    - CORE_BRANCH=master
    # If CORE_BRANCH is empty, it will use the ui-router-core from npm dependencies
    # as specified in package.json
    - CORE_BRANCH=
    # If multiple CORE_BRANCH are listed in the `matrix` section,
    # each one will trigger a SEPARATE job in travis

script:
  - echo "CORE_BRANCH = x${CORE_BRANCH}x";
  - >
    if [ "x${CORE_BRANCH}x" != "xx" ] ; then 
      git clone --depth=10 --branch="${CORE_BRANCH}" https://github.com/ui-router/core.git ui-router-core && npm install ./ui-router-core ;
    fi
  - npm test

sudo: false

git:
  depth: 10

notifications:
  slack: angularbuddies:b6leQM9gkBCW0S7MNDsELpqU
