language: node_js
node_js:
  - "4.1"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma
  - npm install -g typescript
  - ./nodeserver.sh > /dev/null &
  - git clone https://github.com/ui-router/core.git ui-router-core

env: 
  matrix:
    # CORE_BRANCH specifies the branch of ui-router-core to include during build/test
    # If CORE_BRANCH is empty, it will use the ui-router-core from npm dependencies
    # as specified in package.json
    - CORE_BRANCH=
    - CORE_BRANCH=master
     

script:
  - if [ $CORE_BRANCH -ne "" ] ; then git clone https://github.com/ui-router/core.git ui-router-core && pushd ui-router-core && git checkout $CORE_BRANCH && npm install && popd && npm install ./ui-router-core ; fi
  - npm test

sudo: false

git:
  depth: 10

notifications:
  slack: angularbuddies:b6leQM9gkBCW0S7MNDsELpqU
