language: node_js
node_js:
  - "4.1"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma
  - ./nodeserver.sh > /dev/null &
  - git clone https://github.com/ui-router/core.git ui-router-core

script:
  - npm test
  - npm install ./ui-router-core && npm test

sudo: false

git:
  depth: 10

notifications:
  slack: angularbuddies:b6leQM9gkBCW0S7MNDsELpqU
